name: .NET CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/nuget.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # 🛑 Merge conflict detection step (only for pull requests)
      - name: Check for merge conflicts with target branch
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.head_ref }}
          git merge --no-commit --no-ff origin/${{ github.base_ref }} || {
            echo "❌ Merge conflict detected with ${{ github.base_ref }} branch!"
            exit 1
          }

      - name: Restore dependencies
        run: dotnet restore Portify.sln

      - name: Build
        run: dotnet build Portify.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Portify.sln --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

      - name: Upload test results
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/**/*.trx

      - name: Add job summary
        if: always()
        continue-on-error: true
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          if ls TestResults/*.trx 1> /dev/null 2>&1; then
            echo "Test results are available as artifacts." >> $GITHUB_STEP_SUMMARY
          else
            echo "No test results found." >> $GITHUB_STEP_SUMMARY
          fi
